### ISSUE TITLE
Replace Dropbox Backup

### ISSUE THREAD

**Issue by Apocrathia** [Apocrathia/home-assistant-config#22]
My Dropbox if filling up every single time that [this backup automation](https://github.com/Apocrathia/home-assistant-config/blob/master/packages/system_backup.yaml) runs. I need to find another place to store all of my snapshots.

Additionally, the add-on sends EVERY snapshot EVERY time that it runs. It's pretty inefficient to begin with.

**Comment by Apocrathia** [comment]
The following commit disabled Dropbox as a backup location.
Thinking of making a 30 day rotating window for the backups to conserve space. 
https://github.com/Apocrathia/home-assistant-config/commit/878137f7dc50dd31e7c381dc0b25ebc9bbb818c2

**Comment by Apocrathia** [comment]
https://github.com/Apocrathia/home-assistant-config/commit/a1e085f29552b0c96cd00b0b90d81a3bee362a37

**Comment by Apocrathia** [comment]
Will test add-on for a little while and close issue once functionality is verified.

**Comment by Apocrathia** [comment]
This has been officially resolved by the [hass.io Google Drive Backup Addon](https://github.com/sabeechen/hassio-google-drive-backup). Thanks to @sabeechen for making such an awesome tool.

**Comment by sabeechen** [comment]
You're welcome!
